version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_REGION=ca-central-1
      - EDGE_PO RT=4566
      - SERVICES=s3
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"